import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';
import { Menu } from 'antd';
import AntdRegistry from './AntdRegistry';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  { label: <Link href="/">Home</Link>, key: 'home' },
  { label: <Link href="/about">About</Link>, key: 'about' },
  { label: <Link href="/#features">Features</Link>, key: 'features' },
  { label: <Link href="/contact">Contact</Link>, key: 'contact' },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <header>
            <nav style={{ boxShadow: '0 2px 8px #f0f1f2', marginBottom: 24 }}>
              <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
                <div style={{ display: 'flex', alignItems: 'center', height: 64 }}>
                  <span style={{ fontWeight: 700, fontSize: 24, marginRight: 32 }}>IR Infotech</span>
                  <Menu mode="horizontal" items={items} style={{ flex: 1, minWidth: 0, borderBottom: 'none' }} />
                </div>
              </div>
            </nav>
          </header>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
} 